model:
  name: LeNet
  epochs: 150
  batch_size: 64
  learning_rate: 1e-2
  loss: CSE
  optimizer: SGDM
  scheduler: WarmUpPolynomialDecayLR
  test: False
  warmup: 15
  patience: 15
  work: 
    sync_steps: 12
    local_steps: 64
    batch_size: 32
  num_workers: 4
experiment:
  name: train_lenet_cifar100
  resume: False
  version: 0.0
  output: results.csv
checkpoint:
  dir: ./checkpoints
  save_top_k: 3
