model:
  name: LeNet
  epochs: 4
  batch_size: 64
  learning_rate: 2e-2
  loss: CSE
  optimizer: SGDM
  scheduler: CosineAnnealingLR
  test: False
  warmup: 0
  patience: 150
  weight_decay: 1e-3
  work: 
    sync_steps: 88
    local_steps: 4
    batch_size: 64
    dynamic: AvgParamDev
  num_workers: 2
experiment:
  name: train_lenet_cifar100
  resume: False
  version: 0.0
checkpoint:
  dir: ./checkpoints
  save_top_k: 3
