model:
  name: LeNet
  epochs: 150
  batch_size: 64
  learning_rate: 4e-2
  loss: CSE
  optimizer: SGDM
  scheduler: CosineAnnealingLR
  test: False
  warmup: 0
  patience: 0
  weight_decay: 1e-3
  slowmo:
    learning_rate: 1.0
    momentum: 0.6
  work: 
    sync_steps: 22
    local_steps: 8
    batch_size: 64
    dynamic:
      strategy: LossLS
      n_losses: 3
  num_workers: 4
experiment:
  name: train_lenet_cifar100
  resume: False
  version: 0.0
  output: dynamic.csv