model:
  name: LeNet
  epochs: 5
  batch_size: 64
  learning_rate: 1e-3
  loss: CSE
  optimizer: AdamW
  scheduler: try
  pretrained:
  test: False
experiment:
  name: train_lenet_cifar100
  resume: False
  version: 0.0
checkpoint:
  dir: ./checkpoints
  save_top_k: 3