model:
  name: LeNet
  epochs: 15
  batch_size: 64
  learning_rate: 1e-4
  loss: CSE
  optimizer: AdamW
  scheduler: CosineAnnealingLR
  pretrained:
  test: False
experiment:
  name: train_lenet_cifar100
  resume: False
  version: 0.1
checkpoint:
  dir: ./checkpoints
  save_top_k: 3